apiVersion: v1
id: {{ .Values.app_name }}
kind: Route
metadata:
  annotations:
    description: Route for application's service.
  labels:
    application: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  host: {{ .Values.hostname }}
  tls:
    termination: edge
  to:
    name: {{ .Values.app_name }}