apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The web server's http port.
  labels:
    application: {{ .Values.app_name }}
  name: {{ .Values.app_name }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    deploymentConfig: {{ .Values.app_name }}
